accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/agreement/", views.agreement, name="agreement"),
    path("signup/<int:is_seller>/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("mypage/", views.mypage, name="mypage"),
    path("cart/", views.cart, name="cart"),
    path("cart/add/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "cart/add/<int:product_id>/redirect/",
        views.add_cart_redirect,
        name="add_cart_redirect",
    ),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/add/<int:product_id>/", views.add_wishlist, name="add_wishlist"),
    path("review/", views.review, name="review"),
    path("check/", views.check, name="check"),
    path("check_id/", views.check_id, name="check_id"),
    path("check_email/", views.check_email, name="check_email"),
    path("check/update/", views.update, name="update"),
    path("login/naver_callback/", views.naver_callback, name="naver_callback"),
    path("id_check/", views.id_check, name="id_check"),
    path("id_check_naver/", views.id_check_naver, name="id_check_naver"),
    ##
    path("product_management/", views.product_management, name="product_management"),
    ### 내 제품 문의사항 모아보기
    path(
        "question_management/<str:type>",
        views.question_management,
        name="question_management",
    ),
    ### 내가 한 문의사항 모아보기myquestion
    path("myquestion/", views.myquestion, name="myquestion"),
    path("signout/", views.signout, name="signout"),
    ### 팔로잉 버튼
    path("follow/<int:product_user_id>/", views.follow, name="follow"),
    ###팔로잉 리스트
    path("followlist", views.followlist, name="followlist"),
    ### 언팔로잉 버튼
    path("unfollow/<int:product_user_id>/", views.unfollow, name="unfollow"),
    path("orderlist/", views.orderlist, name="orderlist"),
    path("send_valid_number/", views.send_valid_number, name="send_valid_number"),
    path("check_valid_number/", views.check_valid_number, name="check_valid_number"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.root, name="root"),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
    path("products/", include("products.urls")),
    path("qnas/", include("qnas.urls")),
    path("reviews/", include("reviews.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from qnas import views as qnas_views

#
app_name = "products"
urlpatterns = [
    path("<str:type>", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    # path("search", views.search, name="search"),
    path("search/", views.SearchView.as_view(), name="search"),
    #############################################
    # path("cart/", views.cart, name="cart")
    # path("add_cart/<int:pk>", views.add_cart, name="add_cart"),
    # path('<int:pk>/wishlist/', views.wishlist),
    #############################################
    path(
        "<int:pk>/qnas/question/create/",
        qnas_views.question_create,
        name="question_create",
    ),
    path("sale_item/", views.sale_item, name="sale_item"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from products.models import Product

# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None

    name = models.CharField(max_length=150)
    address = models.CharField(max_length=150, blank=True)
    is_seller = models.BooleanField(default=False)

    wishlist = models.ManyToManyField(Product, related_name = 'wishlist_user')
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'following_user')
    carts = models.ManyToManyField(Product, related_name = 'carts_user')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    authenticate,
    update_session_auth_hash,
    get_user_model,
)
from products.models import Product
from reviews.models import Review, ReviewImage
from django.http import JsonResponse
import json
from .models import User
from qnas.models import Question
from django.core.paginator import Paginator
from qnas.models import Question, Answer
from qnas.forms import QuestionForm, AnswerForm
from django.contrib.auth.hashers import check_password

from accounts.decorators import seller_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from collections import defaultdict

from random import random
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from orders.models import Order

# 회원가입 약관
def agreement(request):
    if request.method == "POST":
        data = request.POST.get("buyer") or request.POST.get("seller")

        if data == "buyer":
            is_seller = 0
        else:
            is_seller = 1

        return redirect("accounts:signup", is_seller)

    else:
        return render(request, "accounts/complete/agreement.html")


# 회원가입
def signup(request, is_seller):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save(commit=False).is_seller = is_seller
            form.save()

            return redirect("accounts:login")

    else:
        form = CustomUserCreationForm()

    context = {
        "form": form,
        "is_seller": is_seller,
    }

    return render(request, "accounts/complete/signup.html", context)


# 로그인
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())

            # must change this statement
            return redirect(request.GET.get("next") or "root")

    else:
        form = AuthenticationForm(request)

        # update placeholder in login form(AuthenticationForm)
        form.fields['username'].widget.attrs.update({'placeholder': '아이디를 입력해주세요.'})
        form.fields['password'].widget.attrs.update({'placeholder': '비밀번호를 입력해주세요.'})

    context = {
        "form": form,
    }

    return render(request, "accounts/complete/login.html", context)


# 로그아웃
@login_required
def logout(request):
    auth_logout(request)

    # must change this statement
    return redirect("accounts:login")


# 마이페이지
@login_required
def mypage(request):
    reviews = Review.objects.filter(user=request.user)

    if request.user.is_seller:
        # 상품문의, 새로 작성된 리뷰, 팔로워 수
        # 데이터가 필요하다.
        products = Product.objects.filter(user=request.user)
        questions = Question.objects.filter(product__in=products)

        context = {
            "products": products,
            "reviews": reviews,
            "questions": questions,
        }

    else:
        # 적립금, 쿠폰, 팔로잉 수
        # 주문 내역, 위시리스트 목록, 상품 후기 목록, 상품 문의 목록
        # 데이터가 필요하다.
        questions = Question.objects.filter(user=request.user)

        context = {
            "reviews": reviews,
            "questions": questions,
        }

    return render(request, "accounts/working/mypage.html", context)


# 장바구니
@login_required
def cart(request):
    products = request.user.carts.all()

    context = {
        "products": products,
    }

    return render(request, "accounts/working/cart.html", context)


# 장바구니 상품 추가
@login_required
def add_cart(request, product_id):
    cart = request.user.carts
    product = Product.objects.get(id=product_id)

    if product in cart.all():
        cart.remove(product)
        in_cart = False
    else:
        cart.add(product)
        in_cart = True

    context = {
        "in_cart": in_cart,
    }

    return JsonResponse(context)


# 장바구니 상품 추가 후 장바구니로 리다이렉트
@login_required
def add_cart_redirect(request, product_id):
    cart = request.user.carts
    product = Product.objects.get(id=product_id)

    if product in cart.all():
        cart.remove(product)
    else:
        cart.add(product)

    return redirect("accounts:cart")


# 위시리스트 목록
@login_required
def wishlist(request):
    context = {
        "wishlist": request.user.wishlist.all(),
        "cart": request.user.carts.all(),
    }

    return render(request, "accounts/complete/mypage_wishlist.html", context)


# 위시리스트 상품 추가
@login_required
def add_wishlist(request, product_id):
    user_wishlist = request.user.wishlist
    product = Product.objects.get(id=product_id)

    if product in user_wishlist.all():
        user_wishlist.remove(product)
        is_liked = False
    else:
        user_wishlist.add(product)
        is_liked = True

    context = {"isLiked": is_liked}

    return JsonResponse(context)


# 리뷰 목록
@login_required
def review(request):
    ###페이지 상단에 문의 갯수 표시용
    questions = ""
    if request.user.is_seller:
        # 자신의 판매 상품 리뷰 목록을 보여준다.
        products = Product.objects.filter(user=request.user)
        ###페이지 상단에 문의 갯수 표시용
        questions = Question.objects.filter(product_id__in=products)
        review_image = ReviewImage.objects.all()
        reviews = []
        for product in products:
            reviews += product.review_set.all()
    else:
        # 자신이 작성한 리뷰 목록을 보여준다.
        reviews = Review.objects.filter(user=request.user)
        review_image = ReviewImage.objects.all()
        # reviews_image = Review.objects.prefetch_related("reviewimage_set").filter(
        #     review_id__in=reviews
        # )
    context = {"reviews": reviews, "questions": questions, "review_image": review_image}

    return render(request, "accounts/working/mypage_review.html", context)


# 개인정보 수정 확인(미완성)
def check(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = authenticate(
                username=form.data["username"], password=form.data["password"]
            )
            check = request.user.username == user.get_username()

            if check:
                return redirect("accounts:update")
            else:
                return redirect("accounts:check")

    else:
        form = AuthenticationForm(request)

    context = {"form": form}

    return render(request, "accounts/form.html", context)


# 아이디 중복체크
def check_id(request):
    jsonObject = json.loads(request.body)
    user_id = jsonObject.get("user_id")

    if User.objects.filter(username=user_id):
        is_exist = True
    else:
        is_exist = False

    context = {"is_exist": is_exist}
    return JsonResponse(context)


# 이메일 중복체크
def check_email(request):
    jsonObject = json.loads(request.body)
    user_email = jsonObject.get("user_email")

    if User.objects.filter(email=user_email):
        is_exist = True
    else:
        is_exist = False

    context = {"is_exist": is_exist}
    return JsonResponse(context)


def id_check(request):
    jsonObject = json.loads(request.body)
    username = jsonObject.get("username")
    username = "k" + str(username)
    print(username)
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
    else:
        email = jsonObject.get("email")
        name = jsonObject.get("nickname")
        user = User.objects.create(username=username, email=email, name=name)
        user.save()
    auth_login(request, user, backend="django.contrib.auth.backends.ModelBackend")
    return JsonResponse(
        {
            "username": user.username,
            "email": user.email,
            "name": user.name,
        }
    )


def id_check_naver(request):
    jsonObject = json.loads(request.body)
    username = jsonObject.get("id")
    username = "n" + str(username)
    print(username)
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
    else:
        email = jsonObject.get("email")
        name = jsonObject.get("name")
        user = User.objects.create(username=username, email=email, name=name)
        user.save()
    auth_login(request, user, backend="django.contrib.auth.backends.ModelBackend")
    return JsonResponse(
        {
            "username": user.username,
            "email": user.email,
            "name": user.name,
        }
    )


def naver_callback(request):
    return render(request, "accounts/complete/naver_callback.html")


### 상품정보 관리
@seller_required
def product_management(request):
    if request.user.is_seller:
        # 자신의 판매 상품 목록을 보여준다.
        products = Product.objects.filter(user=request.user)
        questions = Question.objects.filter(product_id__in=products)
        # 입력 파라미터
        page = request.GET.get("page", "1")
        # 페이징
        paginator_all = Paginator(products, 5)
        products = paginator_all.get_page(page)
    else:
        return redirect("accounts:mypage")

    context = {
        "products": products,
        "questions": questions,
    }


templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block body %}

  <div id="wrap">

    <!-- 로그인 폼-->
    <div class="container">
      <h3 class="fw-bold text-center my-5">로그인</h3>
      <div class="row justify-content-center">
        <form action="" method="POST" style="width: 350px;">
          {% csrf_token %}
          <div class="login-input mb-3">
              {{ form.username }}
          </div>
          <div class="login-input">
              {{ form.password }}
          </div>
          <!-- 아이디/비번 찾기 -->
          <div class="d-flex justify-content-end my-3">
              <a class="float-end text-decoration-none small" href="#" style="color: black;">아이디 찾기</a>
              <p class="mx-2 my-0 small">|</p>
              <a class="float-start text-decoration-none small" href="#" style="color: black;">비밀번호 찾기 </a>
          </div>
      
          <!-- 로그인 및 회원가입 버튼 -->
          <div class="row align-items-center mt-4" style="padding: 0px 10px;">
            <button type="submit" class="btn btn-green mb-3 py-3">로그인</button>
            <a href="{% url 'accounts:agreement' %}" type="button" class="btn btn-outline-green py-3 mb-4">회원가입</a>
          </div>
          <div class="row justify-content-center mb-5">
            <a id="naverIdLogin_loginButton" href="javascript:void(0)" class="text-decoration-none p-0 mb-3" style="width: 222px; height:49px;">
              <img src="http://lab.anybuild.co.kr/API/naver/img/naver_g_c_login.PNG" style="width: 222px; height:49px;">
            </a>
            <a id="kakao-login-btn" class="p-0" style="width: 222px; height:49px;"></a>
            <div id="result"></div>
          </div>
          
        </form>
      </div>
    </div>
  </div>
  

  <!--자바스크립트-->
  <script type="text/javascript" src="https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js" charset="utf-8"></script>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://developers.kakao.com/sdk/js/kakao.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script type="text/javascript" src="https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js" charset="utf-8"></script>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script type="text/javascript">
    function unlinkApp() {
      Kakao.API.request({
        url: '/v1/user/unlink',
        success: function(res) {
          alert('success: ' + JSON.stringify(res))
        },
        fail: function(err) {
          alert('fail: ' + JSON.stringify(err))
        },
      })
    }
  </script>
  <script type="text/javascript">
    Kakao.init('f120b1818e7d400b80e5bf358936933a');
    console.log(Kakao.isInitialized());
     
    Kakao.Auth.createLoginButton({
      container: '#kakao-login-btn',
      success: function(authObj) {
        Kakao.API.request({
          url: '/v2/user/me',
          success: function(result) {
            $('#result').append(result);
            id = result.id
            connected_at = result.connected_at
            kakao_account = result.kakao_account
            console.log(kakao_account)
            $('#result').append(kakao_account);
  
            resultdiv="<h2>로그인 성공 !!"
            resultdiv += '<h4>id: '+id+'<h4>'
            resultdiv += '<h4>connected_at: '+connected_at+'<h4>'
            profile_image = "";
            email ="";
            gender = "";
            nickname = "";
            if(typeof kakao_account != 'undefined'){
              email = kakao_account.email;
              profile_image = kakao_account.profile.thumbnail_image_url;
              gender = kakao_account.gender;
              nickname = kakao_account.profile.nickname;
            }

            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
            axios({
              method: 'post',
              url: `/accounts/id_check/`,
              headers: {'X-CSRFToken': csrftoken},
              data: {'username': id, 'email': email, 'profile_image': profile_image, 'nickname': nickname,}
              }).then(response => {
                window.location.replace("/");
              })
          },
          fail: function(error) {
            alert(
              'login success, but failed to request user information: ' +
                JSON.stringify(error)
            )
          },
        })
      },
      fail: function(err) {
        alert('failed to login: ' + JSON.stringify(err))
      },
    })
  </script>
  <script src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js" charset="utf-8"></script>
  <script>
  // http://127.0.0.1:8000/accounts/login
  
  var naverLogin = new naver.LoginWithNaverId(
    {
      clientId: "IKTj6dJebYsENJ_O0JLk", //내 애플리케이션 정보에 cliendId를 입력해줍니다.
      callbackUrl: "http://127.0.0.1:8000/accounts/login/naver_callback/", // 내 애플리케이션 API설정의 Callback URL 을 입력해줍니다.
      isPopup: false,
      // loginButton: {color: "green", type: 3, height: 60}
      callbackHandle: true,
    }
  );	

  naverLogin.init();

  window.addEventListener('load', function () {
  naverLogin.getLoginStatus(function (status) {
    if (status) {
      var email = naverLogin.user.getEmail(); // 필수로 설정할 값
        
      console.log(naverLogin.user); 
        
            if( email == undefined || email == null) {
        alert("이메일은 필수정보입니다. 정보제공을 동의해주세요.");
        naverLogin.reprompt();
        return;
      }
    } else {
      console.log("callback 처리에 실패하였습니다.");
    }
  });
  });


  var testPopUp;
  function openPopUp() {
    testPopUp= window.open("https://nid.naver.com/nidlogin.logout", "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,width=1,height=1");
  }
  function closePopUp(){
    testPopUp.close();
  }

  function naverLogout() {
  openPopUp();
  setTimeout(function() {
    closePopUp();
    }, 1000);


  }
</script>

{% endblock %}

templates/accounts/mypage.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% comment %} 
누르면 옆에 메뉴 active 클래스 추가하게끔 만드는거 미완성 
{% endcomment %}
{% block script %}
<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>
<script>

$("a").on("click", function(e){
    $("a").removeClass("active");
    $("e.target").addClass("active");
});

</script>
{% endblock script %}

{% block body %}

    <!-- 판매자 상품문의 -->
    <hr class="m-0" />

    <!-- 프로필 -->
    <div class="bg-light">
      <div class="container pt-5 pb-4">
        <div class="row">
          <div class="col-sm-5">
            <div class="card">
              <div
                class="d-flex align-items-center mx-4 my-4"
                style="height: 136px"
              >
                <img
                  class="rounded-pill"
                  src="https://picsum.photos/1280/720"
                  alt=""
                  style="height: 80px; width: 80px"
                />
                <div>
                  <p class="mb-2 ms-4 fs-5 fw-bold">{{ request.user.name }} 님</p>
                  <div class="mb-0 ms-4">
                    <p class="mb-1">
                      {% if request.user.is_seller %}
                        판매자 등급
                      {% else %}
                        구매자 등급
                      {% endif %}
                      <span class="text-green fw-bold">대왕 브로컬리🥦</span>
                    </p>
                    <p class="mb-0">{{ request.user.email }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-7">
            <div class="">
              <div class="d-flex">
                {% if request.user.is_seller %}
                  {% comment %} 링크 추가 해야함 {% endcomment %}
                  <a 
                    type="button" 
                    class="card col-4 ms-3 ps-4 text-decoration-none text-dark"
                    href="{% url 'accounts:question_management' 'recent'%}"
                  >
                    <p class="mt-3 mb-0">상품문의 ></p>
                    <p class="fs-4 fw-bold text-green">{{ questions | length }}개</p>
                </a>
                  {% comment %} 링크 추가 해야함 {% endcomment %}
                  <a 
                    type="button" 
                    class="card col-4 ms-3 ps-4 text-decoration-none text-dark"
                    href="{% url 'accounts:review' %}"
                  >
                    <p class="mt-3 mb-0">작성된 리뷰 ></p>
                    <p class="fs-4 fw-bold text-green">{{ reviews | length }}개</p>
                  </a>
                  <button class="card col-4 ms-3 ps-4">
                    <p class="mt-3 mb-0 text-decoration-none text-dark">팔로워</p>
                    <p class="fs-4 fw-bold  text-green">{{ request.user.following_user.all | length }}명</p>
                  </button>
                {% else %}
                  <button class="card col-4 ps-4">
                    <p class="mt-3 mb-0">적립금 ></p>
                    <p class="fs-4 fw-bold text-green">0원</p>
                  </button>
                  <button class="card col-4 ms-3 ps-4">
                    <p class="mt-3 mb-0">쿠폰 ></p>
                    <p class="fs-4 fw-bold text-green">0개</p>
                  </button>
                  <a
                        type="button"
                         class="card col-4 ms-3 ps-4  text-decoration-none text-dark"
                         href="{% url 'accounts:followlist' %}">
                    <p class="mt-3 mb-0">팔로잉 ></p>
                    <p class="fs-4 fw-bold text-green">{{ request.user.followings.all | length }}명</p>
                  </a>
                {% endif %}
              </div>
              <div>
                <div class="d-flex justify-content-between my-3">
                  {% if request.user.is_seller %}
                    <form action="{% url 'products:create' %}" method="POST" class="w-100">
                      {% csrf_token %}
                      <button class="card col-6 p-3 w-100 d-flex align-items-center">
                        <p class="fs-4 fw-bold text-green mb-0" style="margin-top: 2px;">
                          상품등록
                        </p>
                      </button>
                    </form>
                  {% else %}
                    <button class="card col-6 p-4">컬리 그린 박스 ></button>
                  {% endif %}
                  <button class="card col-6 p-4" style="margin-left: 32px">
                    컬리패스 >
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- container -->
    </div>

    <hr class="my-0" />

    <!-- 내역 -->
    <div class="container bg-white">
      <div class="row mx-atuo mb-3 py-3">
        <!-- 탭 목록 -->
        <div class="col-2 my-5">
          <div class="list-group">
            {% if request.user.is_seller %}
            <a
                type="button"
                class="list-group-item list-group-item-action"
                href="{% url 'accounts:product_management' %}"
                 >
                상품 관리
                </a>
              <button
                type="button"
                class="list-group-item list-group-item-action"
              >
                판매 관리
              </button>
              <button
                type="button"
                class="list-group-item list-group-item-action"
              >
                클레임/정산
              </button>
              <a
                type="button"
                class="list-group-item list-group-item-action"
                href="{% url 'accounts:review' %}"
              >
                리뷰
              </a>
            {% else %}
            <a href="{% url 'accounts:orderlist' %}"
              type="button"
              class="list-group-item list-group-item-action"
            >
              주문 내역
            </a>
            <a
              type="button"
              class="list-group-item list-group-item-action"
              href="{% url 'accounts:wishlist' %}"
            >
              위시리스트
            </a>
            <a
              type="button"
              class="list-group-item list-group-item-action"
              href="{% url 'accounts:review' %}"
            >
              상품 후기
            </a>
            <a
              type="button"
              class="list-group-item list-group-item-action"
              href="{% url 'accounts:myquestion' %}"
            >
              상품 문의
            </a>
            {% endif %}
          </div>
          <hr />
          <div class="list-group">
            <a
              type="button"
              class="list-group-item list-group-item-action border-top"
              href="{% url 'accounts:update' %}"
            >
              개인 정보 수정
            </a>
            <a
              type="button"
              class="list-group-item list-group-item-action border-top"
              href="{% url 'accounts:signout' %}"
            >
              계정 삭제
            </a>
          </div>
        </div>
        <!-- 탭 내용 -->
        {% block content %}
        {% endblock content %}
        <!-- 탭 내용-->
      </div>
    </div>

{% endblock body %}

templates/accounts/mypage_following.html
{% extends 'accounts/mypage.html' %}

{% load django_bootstrap5 %}
{% load static %}
{% load humanize %}
{% block content %}
<!-- 팔로잉 페이지 -->
<div class="col-10 py-5 px-5 bg-light" style="padding: 0px 105px">
    <h3 class="ms-3">팔로우한 판매자
      <span>
        {{following.count}}
      </span>
    </h3>
    <hr class="green-line" />
    {%for p in product_%}
        {%for seller in following%}
            {%if p.key == seller.id%}
            <!-- seller1 -->
            <div class="container px-3 my-4">
            <div class="d-flex justify-content-between">
                <p class="fs-5">
                <span class="fw-bold"> {{ seller.name }}</span>
                의 최근 판매상품
                </p>
                <a type="button" href="{%url 'accounts:unfollow' seller.id%}" class="btn btn-outline-green rounded-pill" style="height: 35px; padding-top: 3px">
                팔로우 취소
                </a>
               
            </div>
            <div id="carouselControls" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                <!-- carousel 1 -->
                <div class="carousel-item active">
                    <div class="card-group container mt-3">
                        {%for product in products %}
                            {%for val in p.val %}
                            {%if val == product.id%}
                            <div class="card mx-2 border-0 pro-card"  onclick="location.href='/products/{{product.pk}}/'">
                                    {%if product.is_crawl%}
                                    <img src="{{product.crawl_produt_detail_img}}" class="card-img-top" alt="상품 이미지">
                                    {%else%}
                                    <img src="{{product.produt_thum_img.url}}" class="card-img-top" alt="상품 이미지">
                                    {%endif%}
                            <div class="card-body">
                                <h6 class="card-title">{{product.title}}</h6>
                                <p class="card-text">{{product.price|intcomma}}원</p>
                            </div>
                            </div>
                            {%endif%}
                            {%endfor%}     
                        {%endfor%} 
                </div>
                </div>
            <!-- carousel 2 -->


            </div>
        </div>
        </div>
        <hr />
        {%endif%}

    {%endfor%}
    {%endfor%}
  </div>
{% endblock content %}