pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.root, name="root"),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
    path("products/", include("products.urls")),
    path("qnas/", include("qnas.urls")),
    path("reviews/", include("reviews.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/create/", views.review_create, name="review_create"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/detail/<int:review_pk>", views.review_detail, name="review_detail"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<int:pk>/like/", views.like, name="like"),
]

reviews/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.
from django.conf import settings

star_Choices = (
    ("⭐", "⭐"),
    ("⭐⭐", "⭐⭐"),
    ("⭐⭐⭐", "⭐⭐⭐"),
    ("⭐⭐⭐⭐", "⭐⭐⭐⭐"),
    ("⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"),
)


class Review(models.Model):
    title = models.CharField(max_length=20)
    grade = models.CharField(max_length=10, choices=star_Choices)
    content = models.TextField()
    # image = ProcessedImageField(
    #     upload_to="images/",
    #     blank=True,
    #     processors=[ResizeToFill(1200, 960)],
    #     format="JPEG",
    #     options={"quality": 80},
    # )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_revies"
    )
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="작성일")

    class Meta:
        db_table = "리뷰"
        verbose_name = "리뷰"
        verbose_name_plural = "리뷰"


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="댓글내용")
    created = models.DateTimeField(auto_now_add=True, verbose_name="작성일")
    # deleted = models.BooleanField(default=False, verbose_name='삭제여부')
    # reply = models.IntegerField(verbose_name='답글위치', default=0)
    def __str__(self):
        return self.content

    # @property
    # def created_string(self):
    #     time = datetime.now(tz=timezone.utc) - self.created

    #     if time < timedelta(minutes=1):
    #         return '방금 전'
    #     elif time < timedelta(hours=1):
    #         return str(int(time.seconds / 60)) + '분 전'
    #     elif time < timedelta(days=1):
    #         return str(int(time.seconds / 3600)) + '시간 전'
    #     elif time < timedelta(days=7):
    #         time = datetime.now(tz=timezone.utc).date() - self.created.date()
    #         return str(time.days) + '일 전'
    #     else:
    #         return False

    class Meta:
        db_table = "댓글"
        verbose_name = "댓글"
        verbose_name_plural = "댓글"


# 단일 파일은 도저히 처리 불가능.
# 모델을 새로 만듬.
class ReviewImage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["title"].label = "제목"
        self.fields["title"].widget.attrs.update(
            {
                "placeholder": "제목을 입력해주세요.",
                "class": "form-control",
                "id": "form_title",
                "autofocus": True,
            }
        )
        self.fields["grade"].label = "별점"
        self.fields["grade"].widget.attrs.update(
            {"class": "form-control", "autofocus": False, "style": "width: 40%; "}
        )
        self.fields["content"].label = "내용"
        self.fields["content"].widget.attrs.update(
            {
                "placeholder": "후기를 작성해주세요.",
                "class": "form-control",
                "id": "form_content",
                "autofocus": False,
            }
        )
        # self.fields["image"].label = "첨부 이미지"
        # self.fields["image"].widget.attrs.update(
        #     {"class": "form-control", "autofocus": False, "style": "width: 40%; "}
        # )

    class Meta:
        model = Review
        # fields = ["title", "grade", "content", "image"]
        fields = [
            "title",
            "grade",
            "content",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product

from .forms import ReviewForm, CommentForm
from .models import Review, Comment, ReviewImage
from django.http import HttpResponse, JsonResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {"reviews": reviews}

    return render(request, "reviews/index.html", context)


def detail(request, pk):
    # review = get_object_or_404(Review, pk=pk)
    ##
    # prefetch_related를 통해 review를 상속받는 reveiwimage의 image들을 가져온다.
    # reveiwimage_set의 reveiwimage는 DB에 저장된 이름이다
    # review에 대한 query를 실행해 pk에 대한 리뷰를 받아오고,
    # 가져온 데이터에서 review의 id에 대해 reveiwimage의 query를 실행해 데이터를 가져온다
    review = Review.objects.prefetch_related("reviewimage_set").get(id=pk)
    comment_form = CommentForm()

    context = {
        "review": review,
        "comments": review.comment_set.all(),
        "comment_form": comment_form,
    }

    return render(request, "reviews/detail.html", context)


@login_required
def review_create(request, pk):
    info = Product.objects.get(pk=pk)

    if request.method == "POST":
        # DB에 저장하는 로직
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            new = review_form.save(commit=False)
            new.product_id = info.pk
            new.user = request.user
            new.save()
            for image in request.FILES.getlist("image", None):
                postimage = ReviewImage()
                postimage.image = image
                postimage.review = new
                postimage.user = request.user
                postimage.product_id = info.pk
                postimage.save()
            return redirect("products:detail", info.pk)

    else:
        review_form = ReviewForm()

    context = {"review_form": review_form}

    return render(request, "reviews/form.html", context=context)


def review_detail(request, product_pk, review_pk):
    info = Review.objects.get(pk=review_pk)
    comment_form = CommentForm()

    context = {
        "info": info,
        "comment_form": comment_form,
        "comments": info.comment_set.all(),
    }

    return render(request, "reviews/detail.html", context)


@login_required
def delete(request, pk):
    info = Review.objects.get(pk=pk)
    pro_id = info.product_id
    if info.user == request.user:
        info.delete()
    return redirect("products:detail", pro_id)


@login_required
def update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user == review.user:
        if request.method == "POST":
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                review_form.save()
                messages.success(request, "글이 수정되었습니다.")
                return redirect("reviews:detail", review.pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {"review_form": review_form}
        return render(request, "reviews/form.html", context)
    else:
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("reviews:detail", review.pk)


@login_required
def comment_create(request, pk):
    print(request.POST)
    review = get_object_or_404(Review, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        context = {
            "content": comment.content,
            #'userName': comment.user.username
        }
        return JsonResponse(context)


@login_required
def comment_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    # comment.delete()
    if comment.user == request.user:
        comment.delete()
    return redirect("reviews:detail", pk)


@login_required
def like(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        is_liked = False
    else:
        review.like_users.add(request.user)
        is_liked = True
    context = {"isLiked": is_liked, "likeCount": review.like_users.count()}
    return JsonResponse(context)

templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body %} 
<div class="container container mt-5">
    <div class="card" style="width: 100%;">
        <!--제목,분류,작성일-->
        <div class="card-header pt-4 ps-3">
            <h3 class="text-muted fw-bold">{{ review.title }}</h3>
            <p class="d-flex justify-content-end text-muted">{{review.created|date:"y-m-d"}}</p>
        </div>
        <div class="card-body pt-3 ps-3" style="min-height: 400px; color:black;">
            <!--작성자, 조회수-->
            <div>
                <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ review.user.name }}</span>
                <br>
                <span><i class="fas fa-user-edit"></i>&nbsp;평점 : {{ review.grade }}</span>
            </div>
            <hr>
            <!--내용-->
            {% for image in review.reviewimage_set.all %}
            <div style="overflow:auto">
                <img src="/media/{{image.image}}">
                </div>
                <br/>
            {% endfor %}
            <div class="ps-4">
              {{ review.content|safe}}
            </div>
            <br>
            <div class="d-flex justify-content-center mt-3" style="margin-bottom:-10px; margin-top: -6px;">
                <div type="button" class="btn btn-outline-success">
                  {% if request.user.is_authenticated %}
                      {% if request.user in review.like_users.all %}
                        <i id="like-btn" data-review-id="{{ review.pk }}" class="bi bi-hand-thumbs-up-fill"></i>&nbsp;추천
                      {% else %}
                          <i id="like-btn" data-review-id="{{ review.pk }}" class="bi bi-hand-thumbs-up"></i>&nbsp;추천
                      {% endif %}
                      {%else%}
                      <i id="like-btn" class="bi bi-hand-thumbs-up"></i>&nbsp;추천
                    {% endif %}
                    <span id="like-count" style="margin-left: 5px;">&nbsp;{{ review.like_users.count }}</span>
                  </div>
                </div>
            <div class="d-flex justify-content-end">
                <div class="text-right" style="margin-top:-15px;">
                {% if request.user.is_superuser %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/reviews/{{ review.id }}/update/'">수정</button>
                <button class="btn btn-sm" id="detail_btn" data-bs-toggle="modal" data-bs-target="#delete_modal">삭제</button>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/products/{{ review.product_id }}/'">목록으로</button>
                {% else %}
                
                    {% if request.user == review.user %}
                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/reviews/{{ review.id }}/update/'">수정</button>
                        <button class="btn btn-sm" id="detail_btn" data-bs-toggle="modal" data-bs-target="#delete_modal">삭제</button>
                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/products/{{ review.product_id }}/'">목록으로</button>
                    {% else %}
                        <button class="btn btn-sm" id="detail_btn" onclick="location.href='/products/{{ review.product_id }}/'">목록으로</button>
                    {% endif %}
                {% endif %}
    </div>
  </div>    
            </div>
            <div class="card" style="width: 100%;">
                <div class="card-header">
                    <div class="col-md-12">
                        {% if request.user.is_authenticated %}
                        <form id="comment-form" data-review-id="{{ review.pk }}">
                        {% csrf_token %}
                        {% bootstrap_form comment_form layout='floating'%}
                        <button type="submit" class="btn btn-green ms-4" >댓글달기</button>
                        </form>
                        {%endif%}
                      <hr>
                      <div id="comments">
                            {% for comment in comments %} 
                            <div class="d-flex justify-content-between flex-column">
                                    <div class="d-flex  justify-content-between">
                                        <h6 class="link mx-4">
                                            <div class="title_link fw-bold" >
                                                {{ comment.user.name }}</div>
                                        </h6>
                                        <h6 class="link mx-4">
                                            {{comment.created|date:"y-m-d"}}
                                        </h6>
                                    </div>
                                    <p>
                                    <div class="d-flex  justify-content-between">
                                        <h6 class="mx-4 ms-4 flex-fill">{{ comment.content }} </h6>
                                        <div class="commet-btn">
                                            <form action="{% url 'reviews:comment_delete' comment.review.pk comment.pk %}" method="POST">
                                                {% csrf_token %}
                                                <button class="float-end btn btn-dark btn-sm mx-4">삭제</button>
                                            </form>
                                        </div>
                                    </div>
                                </p>
                            </div>
                          <hr>    
                           {% endfor %}
                    </div>
                </div>
            </div>
            </div>
          </div>   

</div>
<div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
<div class="modal-dialog" role="document">
  <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title">삭제경고</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body">
          <p>게시글을 삭제하시겠습니까?</p>
      </div>
      <div class="modal-footer">
          <button onclick="deleteModal()" type="button" class="btn btn-dark">삭제하기</button>
          <button type="button" class="btn btn-light" data-bs-dismiss="modal">취소하기</button>
      </div>
  </div>
</div>
<script type="text/javascript">
function deleteModal() {
    location.replace('/reviews/{{ review.id }}/delete/');
}
</script>
</div>


           
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    // 댓글!
    // (1) 댓글 폼
    const commentForm = document.querySelector('#comment-form')
    // (2) 제출하면, 함수 실행시킬래 
    // csrf 
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    commentForm.addEventListener('submit', function(event) {
      event.preventDefault();
      axios({
        method: 'post',
        url: `/reviews/${event.target.dataset.reviewId}/comments/`,
        headers: {'X-CSRFToken': csrftoken},
        data: new FormData(commentForm) // 폼에 있는 정보를 data로 넘겨줄 수 있도록 변환
      })
      .then(response => {
        console.log(response.data)
        // 댓글을 추가하는 로직
        const comments = document.querySelector('#comments')
        const p = document.createElement('p')
        p.innerText = `${response.data.userName} | ${response.data.content}`
        const hr = document.createElement('hr')
        comments.append(p, hr) 
        commentForm.reset()
      })
    })
  </script>
      <script>
        // (1) 좋아요 버튼
        const likeBtn = document.querySelector('#like-btn')
        // (2) 좋아요 버튼을 클릭하면, 함수 실행
        likeBtn.addEventListener('click', function (event) {
          // 서버로 비동기 요청을 하고 싶음
          console.log(event.target.dataset)
          axios({
            method: 'get',
            url: `/reviews/${event.target.dataset.reviewId}/like/`
          })
          .then(response => {
            console.log(response)
            console.log(response.data)
            // event.target.classList.toggle('bi-hand-thumbs-up')
            // event.target.classList.toggle('bi-hand-thumbs-up-fill')
            if (response.data.isLiked === true) {
              event.target.classList.add('bi-hand-thumbs-up-fill')
              event.target.classList.remove('bi-hand-thumbs-up')
            } else {
              event.target.classList.add('bi-hand-thumbs-up')
              event.target.classList.remove('bi-hand-thumbs-up-fill')
            }
            const likeCount = document.querySelector('#like-count')
            likeCount.innerText = response.data.likeCount
          })
        })
      </script>

{% endblock %}

templates/reviews/form.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<div class="container">
    {% if request.resolver_match.url_name == 'review_create' %}
    <h2> 상품 후기 작성하기 </h2>
    {% else %}
    <h1> 상품 후기 수정하기 </h1>
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form review_form %}
      
      <input multiple type="file" name="image" accept="image/*" id="id_image">
      <div class="text-center">
        <button class="btn btn-primary btn-xl text-uppercase" >작성 완료</button>
      </div>
    </form>
</div>
{% endblock %}

templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block body %}
<div class="container">
    <div class="header d-flex flex-column justify-content-center align-items-center">
        <h1 class="fs-1 fw-bolder text-white">리뷰 게시판</h1>
      </div>
      
      <div class="row">
        {% for review in reviews %}
        <div class="col-4 my-3">
          <div class="card">
            {% if review.image %}
              <img src="{{ review.image.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="https://dummyimage.com/1200x960/000000/c4c4c4" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ review.title }}</h5>
              
              <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-outline-primary my-3">상세보기</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
</div>
{% endblock %}